SOURCES = 	ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_atoi.c \
			ft_isascii.c \
			ft_isprint.c \
			ft_strlen.c \
			ft_tolower.c \
			ft_toupper.c \
			ft_strchr.c \
			ft_strrchr.c

CFLAGS = -Wall -Wextra -Werror
